const i18Obj = {
  en: {
    addColumn: 'Add a list',
    addTask: 'Add a task',
    back: '← back',
    column: '+ add list',
    create: 'CREATE',
    save: 'SAVE',
    updateBoard: 'Edit board',
    createBoard: 'Create board',
    deleteBoard: 'Are you sure you want to delete this board?',
    deleteColumn: 'Are you sure you want to delete this task list?',
    deleteTask: 'Are you sure you want to delete this task?',
    description: 'Description',
    editTask: 'Edit task',
    errorModal: 'Title is a required field',
    no: 'no',
    required: 'This field is required',
    task: '+ add task',
    title: 'Title',
    yes: 'yes',
  },
  ru: {
    addColumn: 'Добавить список',
    addTask: 'Добавить задачу',
    back: '← назад',
    column: '+ добавить список',
    create: 'СОЗДАТЬ',
    save: 'СОХРАНИТЬ',
    updateBoard: 'Редактировать доску',
    createBoard: 'Создать доску',
    deleteBoard: 'Вы действительно хотите удалить эту доску?',
    deleteColumn: 'Вы действительно хотите удалить данный список задач?',
    deleteTask: 'Вы действительно хотите удалить данную задачу?',
    description: 'Описание',
    editTask: 'Редактировать задачу',
    errorModal: 'Это поле обязательно для заполнения',
    no: 'нет',
    required: 'Данное поле обязательно к заполнению',
    task: '+ добавить задачу',
    title: 'Название',
    yes: 'да',
  },
};

export default i18Obj;
